dist: bionic

language: node_js

services:
  - docker

node_js:
- "8.11"
# - "10"
# - "12"

addons:
  apt:
    packages:
    - kafkacat


cache: npm

before_install:
  - docker run -d -p 9092:9092 -p 2181:2181 -p 2888:2888 -p 3888:3888 mohamnag/kafka-zookeeper
  - kafkacat -b localhost:9092 -L
  - node --version
