dist: bionic
language: node_js
cache: npm
node_js:
- "8.11"
# - "10"
# - "12"

services:
  - docker

addons:
  apt:
    packages:
    - kafkacat
    - redis-server
    - redis-tools


before_install:
  # install kafka
  - docker run -d -p 9092:9092 -p 2181:2181 -p 2888:2888 -p 3888:3888 mohamnag/kafka-zookeeper
  - sleep 60 # wait for kafka

  # install redis
  - redis-cli keys *

  # check kafka
  - kafkacat -b localhost:9092 -L

  # test
  - node --version
