dist: bionic
language: node_js
cache: npm
node_js:
- "8.11"
# - "10"
# - "12"

services:
  - docker
  - redis-server

addons:
  apt:
    packages:
    - kafkacat
    - redis-tools

before_install:
  # install kafka
  - docker run -d -p 9092:9092 -p 2181:2181 -p 2888:2888 -p 3888:3888 mohamnag/kafka-zookeeper
  - sleep 60 # wait for kafka
  - kafkacat -b localhost:9092 -L # check for kafka

  # check redis installation
  - redis-cli keys \*

  # check version
  - node --version

  # copy jest.env
  - cp jest.env.example jest.env
