language: node_js

node_js:
- "8.11"
- "10"
- "12"

cache: npm

before_install:
  - node --version

before_deploy: "npm version patch"
deploy:
  provider: "npm"
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  
